### ISSUE TITLE
Problems on the data endpoint

### ISSUE THREAD

**Issue by flahn** [Open-EO/openeo-grassgis-driver#1]
I have used the Docker deployment approach to setup the service (also created a docker-compose file for easier deployment). 
Most of the exploration endpoints are working, but the `/data` endpoint returns an error. I assume that I haven't downloaded the data within the Dockerfile. Can you tell me where to store the data or how to configure the service?

**Comment by neteler** [comment]
Please use for now the newly created server "openeo.mundialis.de".
We have updated the documentation and config.py accordingly.

**Comment by flahn** [comment]
I tried to interact with the server last Tuesday and it seemed to time-out on basic queries like `/capabilities`, `/data` and `/processes` quite often, so that I was not able to test the openeo-r-client (version: 0.1.0) against the GRASS back-end.
Today, Edzer suggested that we should try to have one more client software that is able to interact with the GRASS back-end, and I wanted to retry it, but the server is not reachable anymore. Can you redeploy it?

**Comment by neteler** [comment]
Sorry, Florian: we have some Firewall problems on the machine. Trying to fix it at time

**Comment by neteler** [comment]
The machine is basically back:
```
curl http://openeo.mundialis.de:5000/processes/zonal_statistics
{
  "args": {
    "imagery": {
      "description": "array of input collections with at least one element that must be of type time series"
    }, 
    "regions": {
      "description": "URL to a publicly accessible polygon file readable by OGR"
    }
  }, 
  "description": "Compute the zonal statistics of a time series using a vector polygon. The following parameters are computed: mean, min, max, mean_of_abs, stddev, variance, coeff_var, sum, null_cells, cells", 
  "process_id": "zonal_statistics"
}
```

**Comment by flahn** [comment]
Thanks, I tried it yesterday and all endpoints were accesible and there were no timeouts.

**Comment by neteler** [comment]
Great!
