### ISSUE TITLE
Missing OPEN-EO Functions

### ISSUE THREAD

**Issue by julian-zeidler** [Open-EO/openeo-grassgis-driver#120]
The following OPENEO  (1.0) core functions are not available in openeo-grassgis-driver:
* aggregate_spatial
* aggregate_temporal
* aggregate_temporal_period
* all
* any
* apply_dimension
* apply_kernel
* aply_neighborhood
* arccos
* arcsin
* arctan
* arctan2
* arcsinh
* arctanh
* array_contains
* array_filter
* array_find 
* array_labels
* between
* ceil
* dimension_labels
* drop_dimension
* first
* floor
* gte
* is_valid
* last
* ln
* log
* order
* pi 
* rename_dimension
* rename_labels
* round 
* sqn
* sin
* sinh
* sort
* tan
* tanh

**Comment by mmacata** [comment]
Hi @julian-zeidler - yes that is right and we don't plan to support all of them. The [specification](https://openeo.org/documentation/1.0/processes.html) says:


> Note: This is the list of all processes specified by the openEO project. Back-ends implement a varying set of processes. Thus, the processes you can use at a specific back-end may derive from the specification, may include non-standardized processes and may not implement all processes listed here. Please check each back-end individually for the processes they support. The client libraries usually have a function called listProcesses or list_processes for that.


in our case this can be found out at `/api/v1.0/processes` in our deployments.

Are there processes missing that you need for a certain use case?

**Comment by metzm** [comment]
At least the missing math processes could be implemented with relatively little effort if that helps. Keep in mind that "Back-ends implement a varying set of processes [...] and may not implement all processes" (https://processes.openeo.org/)

**Comment by marcjansen** [comment]
I'd love to see the math processes being added.

**Comment by metzm** [comment]
Most of the math processes have been added to the backend. Note that back-ends implement a varying set of processes. Thus, the processes you can use at a specific back-end may derive from the specification, may include non-standardized processes and may not implement all processes listed at https://processes.openeo.org/.
