### ISSUE TITLE
Function array_element failing in backend

### ISSUE THREAD

**Issue by julian-zeidler** [Open-EO/openeo-grassgis-driver#121]
Using the array_element function in a Graph fails in the backend in t.rast.bandcalc with expression=(1.2 * data[0])
Running the following code from the python client (0.9)
def my_bandmath(data):
    band1 = array_element(data, index=0)
   # band2 = array_element(data, index=0)
    return 1.2 * band1
datacube.reduce_dimension(dimension="bands",reducer=my_bandmath)
resulting in the Graph
 
{
  "process_graph": {
    "loadcollection1": {
      "process_id": "load_collection",
      "arguments": {
        "id": "nc_spm_08.modis_lst.strds.LST_Day_monthly",
        "spatial_extent": null,
        "temporal_extent": [
          "2015-01-01",
          "2015-03-01"
        ]
      }
    },
    "reducedimension1": {
      "process_id": "reduce_dimension",
      "arguments": {
        "data": {
          "from_node": "loadcollection1"
        },
        "dimension": "bands",
        "reducer": {
          "process_graph": {
            "arrayelement1": {
              "process_id": "array_element",
              "arguments": {
                "data": {
                  "from_parameter": "data"
                },
                "index": 0
              }
            },
            "multiply1": {
              "process_id": "multiply",
              "arguments": {
                "x": 1.2,
                "y": {
                  "from_node": "arrayelement1"
                }
              },
              "result": true
            }
          }
        }
      }
    },
    "saveresult1": {
      "process_id": "save_result",
      "arguments": {
        "data": {
          "from_node": "reducedimension1"
        },
        "format": "GTIFF",
        "options": {}
      },
      "result": true
    }
  }
}

**Comment by metzm** [comment]
The input raster-cube "nc_spm_08.modis_lst.strds.LST_Day_monthly" does not have a bands dimension, therefore this dimension can not be reduced. The process should fail with a DimensionNotAvailable exception if the specified dimension does not exist.

**Comment by julian-zeidler** [comment]
In my understanding is it not essential for any dataset to have a bands dimension (with at least one band).
Therefore i would have expected an access for band1 to work in any case.

**Comment by metzm** [comment]
> In my understanding is it not essential for any dataset to have a bands dimension (with at least one band). Therefore i would have expected an access for band1 to work in any case.

There is no band1 in the dataset. There are no bands at all, thus referring to the first band does not make sense. The process called is `reduce_dimension` with `"dimension": "bands"`. This dimension can only be reduced if there are at least two bands, otherwise there won't be any dimension reduction.
