### ISSUE TITLE
Path variables are not enclosed in curly braces

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-grassgis-driver#16]
From https://openeo.mundialis.de/api/v0.3/:

````
{
  "endpoints": [
    {
      "methods": [
        "GET"
      ], 
      "path": "/processes/<string:process_id>"
    },
...
````

From the API spec:

> Variables in the paths must be placed in curly braces, e.g. `{process_id}`

While it doesn't really matter for a human, this is important for the openEO Hub: It can only detect functionalities as being supported when the paths are correctly formatted. The Hub tolerates different parameter *names*, e.g. your prefix with `string:` is okay. But the enclosing must follow the spec. Otherwise the functionality will be incorrectly reported as non-supported.

BTW your `GET //collections/<string:name>` endpoint has *two* leading slashes, probably a typo?

**Comment by m-mohr** [comment]
I just tried to use the endpoint and encountered the same problems. Would be great to get this solved.

**Comment by AnikaBettge** [comment]
I'm not sure what it's supposed to look like.
Does that only apply to the results of https://openeo.mundialis.de/api/v0.3/ ?
Or is the call https://openeo.mundialis.de/api/v0.3/collections/nc_spm_08.PERMANENT.vector.elev_lidrural_mrptsft wrong and there are missing the curly braces?

**Comment by christophfriedrich** [comment]
It only applies to the results of the `/` endpoint.

Taking the example from my initial issue, the correct version would look like this:

````
{
  "endpoints": [
    {
      "methods": [
        "GET"
      ], 
      "path": "/processes/{string:process_id}"
    },
...
````

I.e. just replace

- `<` with `{`
- `>` with `}`

That's it.

The call https://openeo.mundialis.de/api/v0.3/collections/nc_spm_08.PERMANENT.vector.elev_lidrural_mrptsft is correct; the identifier must not be enclosed in the actual URL.

I had a quick look at your commit: I think it fully fixes this issue.

**Comment by AnikaBettge** [comment]
Okay, thank you very much.

**Comment by mmacata** [comment]
Changes are now deployed: https://openeo.mundialis.de/api/v0.3/ . Please test @christophfriedrich

**Comment by christophfriedrich** [comment]
Thanks, I'd love to test it, but I'm being asked for credentials which I don't know. The "openEO back-end instances" Google Doc says one needs "none" username/password. Please update.

**Comment by christophfriedrich** [comment]
Due to the password protection I didn't test it with the Hub, but it looks fine :ok_hand:

**Comment by christophfriedrich** [comment]
Minor thing that I spotted: All path variables are named `xy_id`, e.g. `process_id`. BUT what would be `collection_id` is called `name`:

````
{
      "methods": [
        "GET"
      ], 
      "path": "/collections/{name}"
    }, 
````

That's fine, as backends are allowed to call these variables whatever they want, but for the sake of consistency you may want to unify that nevertheless.

**Comment by AnikaBettge** [comment]
As per https://open-eo.github.io/openeo-api/v/0.3.0/guidelines-clients/#scope-file-api-category it is `name`. In v0.4 it will be changed to `collection_id`.

**Comment by m-mohr** [comment]
The single source of truth is the [API reference](https://open-eo.github.io/openeo-api/v/0.3.1/apireference/), not the client guidelines. Thanks for the changes. 

I'm facing the same problem than Christoph, I can't connect as authorization is requested. How can we authorize? Authorization shouldn't be in place for the discovery parts...

**Comment by AnikaBettge** [comment]
Okay but it's the same in the API reference: https://open-eo.github.io/openeo-api/v/0.3.1/apireference/#tag/EO-Data-Discovery/paths/~1collections~1{name}/get

**Comment by m-mohr** [comment]
Yes, it is. Just want to make sure you are not relying on the wrong source. ;-)
