### ISSUE TITLE
Implement CORS

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-grassgis-driver#24]
I tried to access the back-end at http://openeo.mundialis.de with the browser-based JavaScript client.

Unfortunately, I can't access it. It seems CORS is not implemented as I get:
```
Access to XMLHttpRequest at 'http://openeo.mundialis.de/api/v0.4/' from origin 'http://editor.openeo.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

It would be great to get CORS support as specified at https://open-eo.github.io/openeo-api/v/0.4.1/cors/

You can easily check it yourself with the Web Editor at http://editor.openeo.org .

**Comment by mmacata** [comment]
I can't reproduce it. With http://editor.openeo.org I get a "moved permanently" error (http redirects to https when redirecting is active). With `curl -X OPTIONS -iL http://openeo.mundialis.de` I receive:

```
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Thu, 04 Jul 2019 08:16:48 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
Location: https://openeo.mundialis.de/

HTTP/1.1 200 OK
Server: nginx
Date: Thu, 04 Jul 2019 08:16:48 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 0
Connection: keep-alive
Allow: HEAD, OPTIONS, GET
Access-Control-Allow-Origin: *
```
This looks fine for me ?

**Comment by m-mohr** [comment]
So you were able to connect with the Web Editor, @mmacata ? I can't, with Chrome and FF.

I tried both https://openeo.mundialis.de and http://openeo.mundialis.de.

Here are some more information from the Network Tab in Chrome:

Request to http://openeo.mundialis.de via http://editor.openeo.org:
1. GET https://openeo.mundialis.de/.well-known/openeo => 301 Moved Permanently
3. GET https://openeo.mundialis.de/.well-known/openeo => Fails with the error posted above.

Request to https://openeo.mundialis.de (SSL) via http://editor.openeo.org:
1. GET https://openeo.mundialis.de/.well-known/openeo => 200 OK
2. GET http://openeo.mundialis.de/api/v0.4/=> 301 Moved Permanently
3. GET https://openeo.mundialis.de/api/v0.4/ => Fails with the error posted above.

Request to https://openeo.mundialis.de (SSL) via https://editor.openeo.org (SSL):
1. GET https://openeo.mundialis.de/.well-known/openeo => 200 OK
2. GET http://openeo.mundialis.de/api/v0.4/=> Fails with:

`Mixed Content: The page at 'https://editor.openeo.org/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://openeo.mundialis.de/api/v0.4/'. This request has been blocked; the content must be served over HTTPS.`

So the first issue here is that https://openeo.mundialis.de/.well-known/openeo returns http URLs in the response, but should return https URLs always.

The second issue (the error posted in the first post) could be (I'm just guessing here) that the `Access-Control-Expose-Headers` is missing. If you do redirects, I think it should include `Location` as value as specified in the docs: https://open-eo.github.io/openeo-api/v/0.4.1/cors/

**Comment by hwbllmnn** [comment]
The CORS headers seem to be working now, I've also fixed the scheme error/wrong base url issue. Now I can open the web editor and see the list of processes.

**Comment by m-mohr** [comment]
Yes, CORS seems to work for discovery now. Thanks!
