### ISSUE TITLE
Endpoint /collections is extremely slow

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-grassgis-driver#49]
Trying to access https://openeo.mundialis.de/api/v1.0/collections leaves one waiting and waiting, until after a minute there is a _504: Gateway time-out_ error. Can this be sped up? Because at the moment, the user cannot know which collections are available...

**Comment by neteler** [comment]
Agreed: we need to speed up the layer parsing in actinia. We'll check how to do that.

**Comment by christophfriedrich** [comment]
Thanks! I believe you already improved some things? I just did a manual crawling for the Hub and was able to GET that URL in "just" 22 seconds. That's still rather long (I'm aiming to set the timeout parameter for the Hub's connections to 10 seconds), but receiving a reply _at all_ already makes me rather happy :D

**Comment by christophfriedrich** [comment]
Most collection details seem to work fine too, but when crawling I'm still getting timeouts for some of them, the IDs of which are:

- nc_spm_08.PERMANENT.vector.zipcodes_wake
- nc_spm_08.landsat.raster.lsat7_2000_30
- nc_spm_08.modis_lst.raster.MOD11B3.A2015152.h11v05.single_LST_Day_6km
- nc_spm_08.modis_lst.raster.MOD11B3.A2015274.h11v05.single_LST_Day_6km
- utm32n.openeo.raster.Sigma0_VH_db_20180204
- utm32n.openeo_bolzano.raster.T32TPS_20180606T102019_B02
- utm32n.openeo_bolzano.raster.T32TPS_20180611T102021_B06
- utm32n.openeo_bolzano.raster.T32TPS_20180613T101019_B09
- utm32n.openeo_bolzano.raster.T32TPS_20180618T101021_B09
- utm32n.openeo_bolzano.raster.T32TPS_20180621T102021_B11
- utm32n.openeo_bolzano.raster.T32TPS_20180621T102021_B8A
- latlong_wgs84.modis_ndvi_global.raster.MOD13C1.A2013129.006.single_CMG_0.05_Deg_16_days_NDVI
- latlong_wgs84.modis_ndvi_global.raster.MOD13C1.A2014193.006.single_CMG_0.05_Deg_16_days_NDVI
- latlong_wgs84.modis_ndvi_global.raster.MOD13C1.A2015017.006.single_CMG_0.05_Deg_16_days_NDVI
- latlong_wgs84.modis_ndvi_global.raster.MOD13C1.A2015209.006.single_CMG_0.05_Deg_16_days_NDVI
- latlong_wgs84.modis_ndvi_global.raster.MOD13C1.A2017081.006.single_CMG_0.05_Deg_16_days_NDVI
- latlong_wgs84.sentinel2A_openeo_subset.raster.S2A_MSIL1C_20170701T111051_N0205_R137_T30SUJ_20170701T111746_B04

I was running this crawl procedure with a timeout of 60sec.

The interesting thing is: For some of these failed collections I tried to open the corresponding URLs in my browser, and for all that I tried it works fine and I get a response almost immediately (after ca. 950ms on average). Is it problematic that the Hub tries to fetch all 300+ collection detail URLs one after the other?

The collection with ID `latlong_wgs84.PERMANENT.strds.ndvi_16_5600m` is interesting too, for it the crawling script reported `Error: Request failed with status code 500` (i.e. no timeout but a proper server error) -- and when I tried in the browser it neither worked nor raised a 500 error, but instead this time I got a 504 Gateway time-out :thinking:

**Comment by metzm** [comment]
Testing with the backend running locally on my machine, the endpoint /collections takes less than 25 sec, still a bit long due to the large number of collections. Of course both the local backend and https://openeo.mundialis.de connect to same actinia instance. The time depends on how busy the actinia instance is.
Querying a specific collection takes less than a second.

**Comment by neteler** [comment]
(FYI: In the works is the move of the actinia backend to a new server infrastructure)

**Comment by m-mohr** [comment]
I just crawled again and requesting all collections (overview and details for all collections) takes about 10 minutes. All other back-ends can be crawled in less than 10 seconds. An improvement would be appreciated (caching?).

**Comment by mmacata** [comment]
We just applied caching for the `/collections` endpoint. This cache is also enabled for all requests behind `/collections`, so requesting individual collections should also be much faster after the cache is filled.

**Comment by m-mohr** [comment]
Great, thanks! Speed has been greatly improved.
Now I don't have enough time anymore to get a coffee while crawling the back-ends for the Hub. ;-)
