### ISSUE TITLE
Missing bbox coordinate breaks fetching of collection details

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-grassgis-driver#50]
I just tried `latlong_wgs84.PERMANENT.strds.ndvi_16_5600m` once more (see last paragraph in https://github.com/Open-EO/openeo-grassgis-driver/issues/49#issuecomment-694165039), this time receiving a response after 1856ms, which was the 500 error ([live example](https://openeo.mundialis.de/api/v1.0/collections/latlong_wgs84.PERMANENT.strds.ndvi_16_5600m)). 

The error page read:

> ValueError: could not convert string to float: 'None'

And in the (very long) traceback the last entry was:
> File "/usr/local/lib/python3.6/dist-packages/openeo_grass_gis_driver-0.0.1-py3.6.egg/openeo_grass_gis_driver/collection_information.py", line *132*, in `get`
`extent = CollectionExtent(spatial=(float(layer_data["west"]), float(layer_data["south"]),`

So I guess it's simply a missing coordinate in the bbox?

**Comment by metzm** [comment]
`latlong_wgs84.PERMANENT.strds.ndvi_16_5600m` is an empty datacube that should not exist, please try instead `latlong_wgs84.modis_ndvi_global.strds.ndvi_16_5600m`.

**Comment by christophfriedrich** [comment]
My issue is not that I need that data. My issue is that this collection is listed in https://openeo.mundialis.de/api/v1.0/collections. The Hub of course tries to crawl ALL collections that are listed there, so it also tries to access `latlong_wgs84.PERMANENT.strds.ndvi_16_5600m`, which results in the 500 error. The Hub doesn't actually care much about that (it just ignores the collection then). But I wanted to give you a heads-up that there's something wrong with the implementation (software should be more robust) and/or data (datacube should not exist).

**Comment by metzm** [comment]
We have deleted this empty datacube. This was an error regarding the data management component. However, it is possible that an empty datacube will be created by a process chain (e.g. wrong mask, wrong bbox filter, wrong temporal filter). Therefore I prefer to keep this issue open, even though the empty datacube `latlong_wgs84.PERMANENT.strds.ndvi_16_5600m` no longer exists.

**Comment by neteler** [comment]
Tested right now after merge of PR #52 : 

https://openeo.mundialis.de/api/v1.0/collections/latlong_wgs84.PERMANENT.strds.ndvi_16_5600m

delivers "`ERROR: Dataset <ndvi_16_5600m@PERMANENT> not found in temporal database`".
Should be ok, right?

**Comment by metzm** [comment]
> https://openeo.mundialis.de/api/v1.0/collections/latlong_wgs84.PERMANENT.strds.ndvi_16_5600m
> 
> delivers "`ERROR: Dataset <ndvi_16_5600m@PERMANENT> not found in temporal database`".

This error is correct, this dataset no longer exists.

**Comment by metzm** [comment]
Closing as fixed.
