### ISSUE TITLE
Error in /collections endpoint

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-grassgis-driver#71]
Hi,

when accessing https://openeo.mundialis.de/api/v1.0/collections the current server response is:

```json
[
  {
    "description": "An internal error occurred while catching strds layers!"
  }, 
  400
]
```

It would be nice if:
1. the HTTP status code would _not_ be a `200 OK` but some `500`, so that accessing clients treat it as "gone wrong" straight away,
2. the response was formatted as a proper error from the API spec,
3. that wouldn't happen at all of course :angel:

**Comment by metzm** [comment]
The error response for the collections endpoint is fixed in #72

**Comment by neteler** [comment]
Kept open till the server response is correct (there is still a deployment issue)

**Comment by neteler** [comment]
Deployment fixed, collections are back:

https://openeo.mundialis.de/api/v1.0/collections
