### ISSUE TITLE
Clean set up, should add gdal to requirements.txt

### ISSUE THREAD

**Issue by ahalota** [Open-EO/openeo-grassgis-driver#84]
I'm starting out on a completely fresh conda environment, following the Installation directions in https://open-eo.github.io/openeo-grassgis-driver/#installation

I am on Windows 10, using conda environments instead of virtualenv, just because I am familiar with it and by default virtualenv did not work for me. 

I am failing tests because gdal is not included under https://github.com/Open-EO/openeo-grassgis-driver/blob/master/requirements.txt 

I'm working out where in the process to install those for this to work.

**Comment by mmacata** [comment]
Hi ahalota, good point.
We run the backend inside a docker container, instructions can be found here: https://github.com/Open-EO/openeo-grassgis-driver/blob/master/docker/Dockerfile. When I remember correctly, we had some version-mismatch issues with gdal from pip and changed it to the alpine package. I am open to maybe add a separate requirements-conda.txt or even add it to the default requirements and we apply the little hack to it that we already apply to Sphinx. You can make a suggestion via pull request if you like.

**Comment by metzm** [comment]
gdal can't be included in https://github.com/Open-EO/openeo-grassgis-driver/blob/master/requirements.txt, instead it needs to be installed with the system's package manager, e.g. for alpine `apk add --no-cache python3 py3-gdal`.

Closing as won't fix.
